apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: php-mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 891376998403.dkr.ecr.us-east-1.amazonaws.com/mysql-db  # Use your custom MySQL image from ECR
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"  # Make sure this matches what you used in your Dockerfile
        - name: MYSQL_DATABASE
          value: "studentdb"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}  # Use Persistent Volume for production use
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: php-mysql-app
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None  # Headless service for internal DNS resolution
